name: MikeJordan
favicon: null
layout_spectrum: 0.013896983815357089
typography_spectrum: 0.761841174447909
title: Mike Jordan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.121176514076069
  lightness: 0.3526435603853315
  saturation: 0.6530266706831753
  rhythmicContrast: 0.6439204711932689
purpose: []
