name: MikeJordan
favicon: null
layout_spectrum: 0.99586
typography_spectrum: 0.24917
title: Mike Jordan
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010101'
    - '#aeaeae'
    - '#d8d8d8'
    - '#4d4d4d'
  brandStrength: 0.121176514076069
  lightness: 0.3526435603853315
  saturation: 0.6530266706831753
  rhythmicContrast: 0.6439204711932689
purpose: []
